name: CI

on:
  push:
    branches:
      - master
      - next-gen
  pull_request:
    branches:
      - master
      - next-gen

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version:
        - 3.6
        - 3.7
        - 3.8
        - 3.9

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip setuptools
        pip install --upgrade tox tox-gh-actions
    - name: Initialize tox envs
      run: |
        tox --parallel auto --notest
    - name: Test with tox
      run: |
        tox --parallel 0
